export const TASK_LIST_BEGIN = 'TASK_LIST_BEGIN'
export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS'
export const TASK_LIST_ERROR = 'TASK_LIST_ERROR'

export const TASK_SELECT_BEGIN = 'TASK_SELECT_BEGIN'
export const TASK_SELECT_SUCCESS = 'TASK_SELECT_SUCCESS'
export const TASK_SELECT_ERROR = 'TASK_SELECT_ERROR'

export const TASK_CREATE_BEGIN = 'TASK_CREATE_BEGIN'
export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS'
export const TASK_CREATE_ERROR = 'TASK_CREATE_ERROR'

export const TASK_UPDATE_BEGIN = 'TASK_UPDATE_BEGIN'
export const TASK_UPDATE_SUCCESS = 'TASK_UPDATE_SUCCESS'
export const TASK_UPDATE_ERROR = 'TASK_UPDATE_ERROR'

export const TASK_DELETE_BEGIN = 'TASK_DELETE_BEGIN'
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS'
export const TASK_DELETE_ERROR = 'TASK_DELETE_ERROR'

export const TASK_RESET =  'TASK_RESET'