export default {
    isFetching: false,
    isSelecting: false,
    isAdding: false,
    isDeleting: false,
    isUpdating: false,
    fetched: false,
    added: false,
    updated: false,
    deleted: false,
    items: [],
    selected: null,
    error: false,
    errorMessage: null,
};
